create table public.instruments (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Row Level Security)
alter table public.instruments enable row level security;

-- Create policies
create policy "Public instruments are viewable by everyone"
    on public.instruments for select
    using ( true );

create policy "Authenticated users can create instruments"
    on public.instruments for insert
    with check ( auth.role() = 'authenticated' );
